[package]
name = "otils"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
rand = "0.9.2"

[build-dependencies]
cc = "1.0"

[package.metadata.fortanix-sgx]
stack-size=0x400000
heap-size=0x100000000
threads=9
